### PR TITLE
P1 fixes for 1.14 release

### LINKED ISSUE #336: Toggling Tracking from iOS Settings During Onboarding Causes Infinite Spinner on Phone Number Verification Step
### Current behavior

Changing Data tracking toggle in Settings > Privacy > Tracking During Phone Verification produces an infinite spinner during step 4 of the onboarding flow.

### Desired behavior

Toggling the App Tracking iOS Settings either 'on' or 'off' should not noticeably impact the onboarding flow.

### Steps to Reproduce

1. Launch the app on the iOS device.
2. Select 'Ask App Not to Track' or 'Allow'.
3. Continue Education onboarding and complete steps 1 -3.
4. Make sure you're on step 4.
5. Background the app and navigate to Settings > Privacy > Tracking and flip the toggle for Valora.
6. Attempt to reopen the app - **crashes several times.**
7. When does Valora opens user is served step 4 of 5 (phone verification) with an infinite spinner.

### Versions
Valora 1.14.0 on iPhone 11 iOS 14.5

### Attachments
[Video](https://drive.google.com/file/d/1XfZ4ni7Fpw57Yt6iC299-bOY9lfIZZvL/view?usp=sharing)
[Logs](https://drive.google.com/file/d/1XiTyufk7UM_sUQdLVWIwHQV1X6CfPZqN/view?usp=sharing)

### Notes
If Komenci is down user is redirected to the verification step from the home section with the same infinite spinner (unless they have previously skipped)

### Workaround
Once the user successfully launches to app they can skip phone number verification and navigate to the home screen.

### LINKED ISSUE #339: “Enter pin” is asking every time when user kill & relaunch the app if user signup through create new account. .
**Frequency:** 100%
**Repro on build version:** Android internal build V1.14.0 (1004294350) & Test Flight build V1.14.0(58)
**Does not repro version** App Store build 1.12.2	, Play Store build 1.12.2, Test Flight build V1.13.1(56).Android internal build V1.13.1(1004294349) 
**Repro on devices:** One plus 6T (10),Samsung Galaxy Note 5(7),iPhone XR (14.2), iPhone 6+(12.4.5) , 
**Pre-Condition:** 

- Make user user should Complete phone number verification through create new account .
- Make sure “Require PIN on app open” toggle button should disable

  
   **Repro Steps:**

1. Launch the application 
2. Complete onboarding education
3. Tap on create new account 
4. Enter pin
5. Enter phone number 
6. Tap on start button/ Skip the verification flow 
7. Wait for phone number confirming screen
8. Complete verification flow 
9. Kill & relaunch the app 
10. Observe enter pin is shown

 

**Current Behavior:** Enter pin is asking everytime when user kill & relaunch the app. 
**Expected Behavior:**  Enter pin should not ask  everytime when user kill & relaunch the app if “Require PIN on app open” toggle button is disable
**Observation:** Enter pin is not asked when user signin through restore account. 
**Impact:** Bad user experience . 
**Attachment:**  [EnterPIN.mp4](https://drive.google.com/file/d/1MzNyllu4bIdTtwvYAZU-qeAOSgsaeroy/view?usp=sharing)

### LINKED ISSUE #341: “Continuous loading” indicator is show on phone number page when user kill & relaunch the app if user is on Phone number page.
**Frequency:** 100%
**Repro on build version:** Android internal build V1.14.0 (1004294350) & Test Flight build V1.14.0(58)
**Does not repro version** App Store build 1.12.2	, Play Store build 1.12.2, Test Flight build V1.13.1(56).Android internal build V1.13.1(1004294349) 
**Repro on devices:** One plus 6T (10),Samsung Galaxy Note 5(7),iPhone XR (14.2), iPhone 6+(12.4.5) , 

   **Repro Steps:**

1. Launch the application 
2. Complete onboarding education
3. Tap on create new account 
4. Enter pin
5. KIll & relaunch the app when user is on phone number 
6. Enter pin 
7. Observe 

**Current Behavior:** Loading indicator is shown. 
**Expected Behavior:**  Phone number page should show 
**Impact:** User get blocked to continue verification. 
**Attachment:**  [LoadingIndicatoronPhoneNumberPage.mp4](https://drive.google.com/file/d/1BeXJQRPl5YJwY-0oePAHyl3SxotPmVh3/view?usp=sharing)
[Logs](https://drive.google.com/file/d/1jyQxdpN3gMWZQ3qe3wUn9u-NZdU8mwA0/view?usp=sharing )

### LINKED ISSUE #349: Unable to see phone number for contacts with multiple phone numbers
### Current behavior

Unable to see phone number for contacts with multiple phone numbers, making it impossible to distinguish them.

See Slack thread: https://celo-org.slack.com/archives/C018VLA3YAK/p1620685865392600

### Desired behavior

Phone number should be shown under each contact.

### Steps to Reproduce

1. Have a contact with 2 phone numbers
2. Go to the send screen and notice you see the contact twice, but it's impossible to tell the actual phone number as only the number is shown.

### Versions

Valora 1.14.0
Valora <= 1.14.0 is not affected by this issue.

### PR DESCRIPTION
**Pull request by gnardini**
### Description

This PR includes 3 fixes:
- Continuous loading” indicator is show on phone number page when user kill & relaunch the app if user is on Phone number page -> The saga was not being initialized on time to handle actions. We now wait on the saga to be ready before firing actions.
- Unable to see phone number for contacts with multiple phone numbers -> We now show it.
- Enter pin” is asking every time when user kill & relaunch the app if user signup through create new account -> We now only try to register the key if the user has a balance, so this will likely not happen and if it does only once.

### Other changes

N/A

### Tested

Manually on the simulator

### How others should test

- For the continuous loading indicator, create a new account and kill the app on the verification screen. Open it again and see that the loading indicator doesn't last forever.
- After creating a new account, kill the app and open it several times. See that the PIN is not asked.
- Try to send to a contact. Check that you can see their phone number

### Related issues

- Fixes #339
- Fixes #341
- Fixes #349
- Fixes #336

### Backwards compatibility

N/A

### CODE REVIEW

File: packages/mobile/src/web3/dataEncryptionKey.ts [hunk 1]
```diff
@@ -133,6 +135,19 @@ export function* registerAccountDek() {
...
+    if (
+      (stableBalance === null || stableBalance === '0') &&
+      (celoBalance === null || celoBalance === '0')
+    ) {
+      Logger.debug(
+        `${TAG}@registerAccountDek`,
+        'Skipping DEK registration because there are no funds'
+      )
+      return
+    }
```
Comment (jeanregisser) [inline packages/mobile/src/web3/dataEncryptionKey.ts:149]: Looks like we should do the analytics track event after this check instead.

**Review by jeanregisser — COMMENTED** [review]
Awesome

File: packages/mobile/src/recipients/RecipientItem.tsx [hunk 2]
```diff
@@ -39,9 +39,7 @@ class RecipientItem extends React.PureComponent<Props> {
             <Text numberOfLines={1} ellipsizeMode={'tail'} style={styles.name}>
               {getDisplayName(recipient, t)}
             </Text>
-            {!recipient.name ? (
```
Comment (isabellewei) [inline packages/mobile/src/recipients/RecipientItem.tsx:42]: This was my mistake, it should be `{recipient.name ? (`, but I don't think we should get rid of the conditional statement, or else if a recipient doesn't have a name, it will display their phone number/account address twice

**Review by jeanregisser — APPROVED** [review]
Thanks so much!! 🚀 🎉

**Comment by Celoqa** [comment]
Hi @jeanregisser @gnardini we have verified all P1 fixes issue for 1.14 release in latest  internal  build V1.14.1 & Test Flight build V1.14.0(59) and updated the status in respective tickets.
Thanks!
