### PR TITLE
Initialize sentry earlier

### LINKED ISSUE #327: SyntaxError: JSON Parse error: Unexpected token:  
Sentry Issue: [CELO-MOBILE-385](https://sentry.io/organizations/celo/issues/2135244991/?referrer=github_integration)

```
SyntaxError: JSON Parse error: Unexpected token: 
  at parse (native)
  at persistConfig.deserialize (src/redux/store.ts:43:17)
  at apply (native)
...
(10 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by etuleu**
### Description

Moved sentry init earlier in order to catch errors that might happen during redux store loading.

### Other changes

Also updated the getStoredState function to not return empty strings.

The actual error that was happening in production was the database throwing an error like:

> 05-04 18:11:12.912 24367 24456 I ReactNativeJS: redux/store :: Failed to retrieve redux state. :: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it. in Error: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly

This happend because when the store reached a size of about 2MB the read would fail. The way the redux library stores the data is all in one row in the database, which is not great for our use case. Anyway we have moved away from using AsyncStorage since then but just in case any error, such as during a migration happens in the future we will hopefully catch it early before shipping to production.

### Tested

Manually. Threw an exception in store.getStoredState and noticed it does not get captured by sentry because it is not initialized at the time.

### Related issues

- Fixes #327 

### Backwards compatibility

Yes.

### CODE REVIEW

File: packages/mobile/src/sentry/Sentry.ts [hunk 1]
```diff
@@ -7,8 +7,17 @@ import { currentAccountSelector } from 'src/web3/selectors'
...
+
+if (SENTRY_ENABLED) {
+  installSentry()
+} else {
+  Logger.info(TAG, 'Sentry not enabled')
+}
+
 // This should be called as early in the lifecycle of the app as possible.
-export async function installSentry() {
+async function installSentry() {
```
Comment (etuleu) [inline packages/mobile/src/sentry/Sentry.ts:20]: question: does this have to be async?

Comment (etuleu) [reply packages/mobile/src/sentry/Sentry.ts]: If i keep it async then I get a lint error when I call it above.

Comment (jeanregisser) [reply packages/mobile/src/sentry/Sentry.ts]: Seems `async` is not necessary 👍
