### PR TITLE
[Wallet] Fix `getAttestationCodeForSecurityCode` not logging error details

### LINKED ISSUE #371: Unhelpful `identity/verification@attestationCodeReceiver :: Error processing attestation code :: unknown` log
### Current behavior

We found user logs containing `identity/verification@attestationCodeReceiver :: Error processing attestation code :: unknown`, when verification fails, which isn't helpful for debugging.
See Slack thread: https://celo-org.slack.com/archives/C01QQPXC5U6/p1620324188011600

### Desired behavior

The log should show the actual error instead of `unknown`, so we can understand what's happening.

### PR DESCRIPTION
**Pull request by jeanregisser**
### Description

Fix `getAttestationCodeForSecurityCode` not logging error details.
Also handle case where no matching issuer is found and add unit tests.

### Tested

Added unit tests.

### How others should test

1. Start verification process
2. Manually input incorrect verification codes on purpose
3. Check app logs and ensure `identity/verification@attestationCodeReceiver :: Error processing attestation code` shows the real error and NOT `unknown`

### Related issues

- Fixes #371

### Backwards compatibility

Yes

### CODE REVIEW

File: packages/mobile/src/identity/securityCode.ts [hunk 1]
```diff
@@ -78,7 +90,7 @@ async function requestValidator(
       securityCode,
     }
 
-    return attestationsWrapper.getAttestationForSecurityCode(
+    return await attestationsWrapper.getAttestationForSecurityCode(
```
Comment (jeanregisser) [inline packages/mobile/src/identity/securityCode.ts:93]: This was the original problem causing the actual error log not to be logged.
See https://celo-org.slack.com/archives/CL7BVQPHB/p1621254448334500

**Review by gnardini — APPROVED** [review]
Great find and added tests :)

**Comment by Celoqa** [comment]
Hey @jeanregisser I have verified this issue using latest released Android internal build & Test Flight Build V1.14.2 & observed following:
**Observations:** 


- [x] User is able to see "identity/verification@attestationCodeReceiver :: Error processing attestation code" when user take logs by submitting Incorrect code after "Invalid Confirmation Code" validation message occurs. [Attachment](https://drive.google.com/file/d/12rZuUH_W0zxaEGIzu4KRIHvo-_V2P6nn/view?usp=sharing)


**Verified On Devices:** iPhone SE (14.2), Redmi Note 8(9.0)
Thanks..!!
