### PR TITLE
Fix for issue #123

### LINKED ISSUE #123: User not able to receive activity in the recent section on home screen when user B log in & verify phone  number through invite link.
**Frequency:** 100%
**Repro on build version:** Play store Build V1.11.1, App store build V1.11.1
**Repro on devices:** Samsung Galaxy A5(7.0), Realme 6i(10.0),iPhone SE (13.6.1)
**Testing Account:**  (515) 808 5659 / [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B69) 
**Pre-condition:** User  should send dollar through an invitation to user B
**Repro Steps:**
1. Launch the application & login with a test account.
2. Now send money to non verified user from send contact screen & tap on “Send & Invite” option on Sending screen & invite to user B.
3. Now login with the same invitation link & same phone number as user B.
4. Now perform verification flow & go to Home screen.
5. Now user B’s account should be credited with money sent by user A.
6. Observed that,
**Current Behavior:**   No activity displayed in Recent section on home screen after receiving money.
**Expected Behavior:**  Activity should display in the Recent section as the user received money.
**Investigation:** Users are able to see In-App notification.
**Impact:** Users are not able to get ideas behind receiving money.
**Attachment:**  [NoActivityInRecentSection.mp4](https://drive.google.com/file/d/1JukEwdauha7lH1_OdfjkSXw76jSWXsyu/view?usp=sharing)

### PR DESCRIPTION
**Pull request by eruizgar91**
### Description
Chech escrow that has 2 transfers. This happen cause Komenci deploy a wallet that makes the Metatransaction. Now we support the 2 possible escrow cases.

### Other changes

_Describe any minor or "drive-by" changes here._

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### Related issues

- Fixes #123 
### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### CODE REVIEW

File: packages/blockchain-api/src/events/EscrowReceived.ts [hunk 1]
```diff
@@ -7,8 +7,10 @@ import { Contracts } from '../utils'
 export class EscrowReceived extends TransactionType {
   matches(transaction: Transaction): boolean {
     return (
-      transaction.transfers.length === 1 &&
-      transaction.transfers.containsTransferFrom(Contracts.Escrow)
+      (transaction.transfers.length === 1 &&
```
Comment (carterqw2) [inline packages/blockchain-api/src/events/EscrowReceived.ts:10]: When there are too many conditions, it could be nice to make those checks more readable, so the next dev could understand what is going on:
```
return (
    isEscrowReceivedToEOA(transaction) || 
    isEscrowReceivedToMTW(transaction)
)
```

File: packages/blockchain-api/src/events/EscrowReceived.ts [hunk 2]
```diff
@@ -7,8 +7,10 @@ import { Contracts } from '../utils'
...
+        transaction.transfers.containsTransferFrom(Contracts.Escrow)) ||
+      (transaction.transfers.length === 2 &&
+        transaction.transfers.containsAddressToEqualFromAdress(Contracts.Escrow))
```
Comment (carterqw2) [inline packages/blockchain-api/src/events/EscrowReceived.ts:13]: I think we could keep the logic of `TransferNavigator` generic enough without making methods too specific. You could just check that there are two transfers and that there is a transfer from the escrow contract and there is a transfer to the wallet address (account hash). In this case we can drop the `containsAddressToEqualFromAdress` altogether.

**Review by carterqw2 — CHANGES_REQUESTED** [review]
Could you also please add a test for this scenario?

File: packages/blockchain-api/test/blockscout.test.ts [hunk 3]
```diff
@@ -934,4 +934,161 @@ describe('Blockscout', () => {
...
   })
+  it('should handle as escrow the meta-transactions coming from Komenci', async () => {
+    const result = await blockscoutAPI.getTokenTransactions({
+      address: '0x566ce6b765f038a98b5753ced0a65fd49aa0a07c',
+      token: 'cUSD',
+      localCurrencyCode: 'USD',
+    })
+
+    const transactions = result.reverse()
+    expect(transactions).toMatchInlineSnapshot(`
```
Comment (carterqw2) [inline packages/blockchain-api/test/blockscout.test.ts:945]: I can't see that the result contains an event for block # 6203333 that matches the input you defined [here](https://github.com/celo-org/wallet/pull/276/commits/d1f833d077e8c3a0ff58b14eeaf47688a1ef59ae#diff-92da2c52d25b4d0dd3ead6bd5db36b01f0b44fa6447c101fca21424ca08906d2R592). Also, I believe you could just update the test case before that checks that the cUSD feed is correct as this new Escrow case should fall into that bucket.

Comment (carterqw2) [reply packages/blockchain-api/test/blockscout.test.ts:945]: Ah, interesting, the fee is paid in cGLD, so that would be categorized as a cGLD transaction according to [this](https://github.com/celo-org/wallet/blob/main/packages/blockchain-api/src/transaction/Transaction.ts#L74).

File: packages/blockchain-api/src/events/EscrowReceived.ts [hunk 4]
```diff
@@ -7,8 +7,8 @@ import { Contracts } from '../utils'
 export class EscrowReceived extends TransactionType {
   matches(transaction: Transaction): boolean {
     return (
-      transaction.transfers.length === 1 &&
-      transaction.transfers.containsTransferFrom(Contracts.Escrow)
+      transaction.transfers.isEscrowReceivedToEOA(Contracts.Escrow) ||
```
Comment (carterqw2) [inline packages/blockchain-api/src/events/EscrowReceived.ts:10]: `isEscrowReceivedToEOA` and `isEscrowReceivedToMTW` are very specific to the `EscrowReceived` class, so it doesn't make sense to move them to `TransfersNavigator` as no other code would reuse them anyway. Instead we could move them here and get rid of the parameter as both methods would be able to get the address directly.

File: packages/blockchain-api/src/transaction/TransfersNavigator.ts [hunk 5]
```diff
@@ -85,6 +85,20 @@ export class TransfersNavigator {
     )
   }
 
+  isEscrowReceivedToEOA(senderAddress: Contracts | string): boolean {
+    return this.transferCollection.length === 1 && this.containsTransferFrom(senderAddress)
+  }
+
+  isEscrowReceivedToMTW(senderAddress: Contracts | string): boolean {
+    const transfer = this.getTransferFrom(senderAddress)!
```
Comment (carterqw2) [inline packages/blockchain-api/src/transaction/TransfersNavigator.ts:93]: If we move this method to `EscrowReceived`, we can make names of these variables more readable.
```
const transferToAcccount = this.getTransferFrom(Contracts.Escrow)
const transfertoWallet = this.getTransferFrom(transferToAccount.toAddressHash) 
```

File: packages/blockchain-api/test/mockTokenTxs.ts [hunk 6]
```diff
@@ -586,6 +586,41 @@ const mockTokenTxs = {
...
+                  node: {
+                    fromAddressHash: '0xc85d6ccf22499898ea76aa8b7ba89a7ceddbe434',
+                    toAddressHash: '0x566ce6b765f038a98b5753ced0a65fd49aa0a07c',
+                    token: 'cUSD',
+                    value: '20000000000000000000',
+                  },
+                },
+              ],
+            },
+            feeToken: 'cUSD',
```
Comment (carterqw2) [inline packages/blockchain-api/test/mockTokenTxs.ts:613]: You can't just change it `cUSD` as it would be `cGLD` in Blockscout and cUSD transactions would contain additional transfers (which are not currently present in the `edges` array). If you change it back to `cGLD`, you'll notice that the transaction type is not recognized again, and, hence, is missing from the feed in both test cases.

Also, the code relies on the presence of the `toAccountHash` attribute that is not here and you haven't updated the graphQL query to fetch it from Blockscout.

**Review by carterqw2 — CHANGES_REQUESTED** [review]

**Review by carterqw2 — APPROVED** [review]
Looks good!
