### PR TITLE
CICO firebase function event log parser

### LINKED ISSUE #927: Recover events from failed CICO webhook invocations
Calls to our CICO event webhooks will sometimes fail due to providers including new properties in their event objects, which results in BigQuery errors when attempting to store them.

We need to create a script that will recover "missed" events from the firebase function logs and store them in the appropriate table.

### PR DESCRIPTION
**Pull request by tarikbellamine**
### Description
This PR is for an event log parser that will take an input of locally saved Firebase function event logs, parse them, then store them in the appropriate BigQuery table. This is useful because sometimes the Firebase function webhook that should be parsing events fails so this ensures that we don't lose any data due to failures.

### Other changes
- Made the `config` file local friendly by adding optional chaining to params that aren't relevant to the parser
- Removed `BIGQUERY_PROVIDER_STATUS_TABLE` as it's no longer in use

### Tested
Manually

### How others should test
N/A

### Related issues
- Fixes #927

### Backwards compatibility
Yes

### CODE REVIEW

File: packages/cloud-functions/src/bigQuery.ts [hunk 1]
```diff
@@ -15,6 +15,27 @@ export const trackEvent = async (table: string, row: any) => {
...
+}
+
+export const deleteDuplicates = async (table: string) => {
+  try {
+    if (!gcloudProject) {
+      throw new Error('No GCloud Project specified')
+    }
+
+    const sqlQuery = `
+      CREATE OR REPLACE TABLE ${bigQueryProjectId}.${bigQueryDataset}.${table}
```
Comment (gnardini) [inline packages/cloud-functions/src/bigQuery.ts:31]: If it's creating it, will this work? Since it's doing a select from the same table. I'm not very familiar with this `CREATE OR REPLACE TABLE` statement.

Is it possible to add a constraint at a db level for whatever columns should be distinct instead?

File: packages/cloud-functions/src/cico/logParser/parseEventLogs.ts [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+process.env.GCLOUD_PROJECT = project
+// Using an in-line require because process variables need to be defined
+// before calling these functions
+const { parseMoonpayEvent, MOONPAY_BIG_QUERY_EVENT_TABLE } = require('../moonpayWebhook')
+const { parseRampEvent, RAMP_BIG_QUERY_EVENT_TABLE } = require('../rampWebhook')
+const { parseXanpoolEvent, XANPOOL_BIG_QUERY_EVENT_TABLE } = require('../xanpoolwebhook')
+const { parseTransakEvent, TRANSAK_BIG_QUERY_EVENT_TABLE } = require('../transakWebhook')
+
+const selectEventParser = (provider: Providers): Function => {
+  if (provider === Providers.Moonpay) {
```
Comment (gnardini) [inline packages/cloud-functions/src/cico/logParser/parseEventLogs.ts:20]: nit: Could this be a `switch` statement?

File: packages/cloud-functions/src/cico/logParser/parseEventLogs.ts [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+    return parseXanpoolEvent
+  }
+  if (provider === Providers.Transak) {
+    return parseTransakEvent
+  }
+
+  return () => ({})
+}
+
+const selectEventTable = (provider: Providers): string => {
```
Comment (gnardini) [inline packages/cloud-functions/src/cico/logParser/parseEventLogs.ts:38]: Maybe we can combine this with `selectEventParser` and return both things in a `{ parser, eventTable }` object?

**Review by gnardini — COMMENTED** [review]
This is fine to be able to run locally for now, but it requires someone to be monitoring, pulling the logs and running this every now and then.

Is there a plan to automate this somehow? I can imagine one possibility to be to store the payloads on Firebase and mark them as processed  (or delete them) when they are. Then maybe have another cloud function that can be run to re-process failed events? Maybe you can think or another solution as well.

File: packages/cloud-functions/src/bigQuery.ts [hunk 4]
```diff
@@ -15,6 +15,27 @@ export const trackEvent = async (table: string, row: any) => {
...
+      AS
+      SELECT DISTINCT * FROM ${bigQueryProjectId}.${bigQueryDataset}.${table}
+    `
+
+    await bigQuery.query(sqlQuery)
+  } catch (error) {
+    console.error(error)
```
[the remark this answers is not in the document]
Comment (tarikbellamine) [reply packages/cloud-functions/src/bigQuery.ts:38]: Yeah, meant to delete that. Thanks

File: packages/cloud-functions/src/cico/logParser/parseEventLogs.ts (hunk 3 above)
Comment (tarikbellamine) [reply packages/cloud-functions/src/cico/logParser/parseEventLogs.ts:38]: Yep good suggestion

File: packages/cloud-functions/src/cico/logParser/parseEventLogs.ts (hunk 2 above)
Comment (tarikbellamine) [reply packages/cloud-functions/src/cico/logParser/parseEventLogs.ts]: Yeah I guess that would save some lines

File: packages/cloud-functions/src/bigQuery.ts (hunk 1 above)
Comment (tarikbellamine) [reply packages/cloud-functions/src/bigQuery.ts:30]: This won't work well for creating a new table from scratch but I don't think that's a problem because that's outside of the scope of this script. I am mainly doing this because some providers will send certain events multiple times.

**Comment by tarikbellamine** [comment]
> Is there a plan to automate this somehow? I can imagine one possibility to be to store the payloads on Firebase and mark them as processed (or delete them) when they are. Then maybe have another cloud function that can be run to re-process failed events? Maybe you can think or another solution as well.

That's a good suggestion that I've considered. Ultimately decided not to do it right now because I'm not sure the time investment is worthwhile given the team backlog and resourcing at the moment. Certainly an area of improvement we should look to work on when bandwidth allows.

File: packages/cloud-functions/src/cico/logParser/parseEventLogs.ts [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+// before calling these functions
+const { parseMoonpayEvent, MOONPAY_BIG_QUERY_EVENT_TABLE } = require('../moonpayWebhook')
+const { parseRampEvent, RAMP_BIG_QUERY_EVENT_TABLE } = require('../rampWebhook')
+const { parseXanpoolEvent, XANPOOL_BIG_QUERY_EVENT_TABLE } = require('../xanpoolwebhook')
+const { parseTransakEvent, TRANSAK_BIG_QUERY_EVENT_TABLE } = require('../transakWebhook')
+
+const selectEventParserAndTable = (
+  provider: Providers
+): undefined | { parser: Function; table: string } => {
+  switch (provider) {
```
Comment (gnardini) [inline packages/cloud-functions/src/cico/logParser/parseEventLogs.ts:22]: Something I like to do in cases like this is create an object and evaluate it directly like this instead of the switch statement:
```
return {
  [Providers.Moonpay]: { parser: parseMoonpayEvent, table: MOONPAY_BIG_QUERY_EVENT_TABLE },
  [Providers.Ramp]: { parser: parseRampEvent, table: RAMP_BIG_QUERY_EVENT_TABLE },
  [Providers.Xanpool]: { parser: parseXanpoolEvent, table: XANPOOL_BIG_QUERY_EVENT_TABLE },
  [Provicers.Transak]: { parser: parseTransakEvent, table: TRANSAK_BIG_QUERY_EVENT_TABLE },
}[provider]
```

totally optional of course, I just like the way it ends up looking :)

**Review by gnardini — APPROVED** [review]
🚀

File: packages/cloud-functions/src/cico/logParser/parseEventLogs.ts (hunk 5 above)
Comment (tarikbellamine) [reply packages/cloud-functions/src/cico/logParser/parseEventLogs.ts:22]: Oh yeah that's more compact, thanks for the suggestion. It's a bit more annoying in this case because not every provider has a property (there is no key for Simplex because it's not a webhook and doesn't really have logs to parse) so typescript complains.
