### PR TITLE
Fix for toUpperCase error

### LINKED ISSUE #241: TypeError: Cannot read property 'toUpperCase' of null
Sentry Issue: [CELO-MOBILE-4RS](https://sentry.io/organizations/celo/issues/2339158743/?referrer=github_integration)

```
TypeError: Cannot read property 'toUpperCase' of null
  at nameCompare (src/recipients/recipient.ts:216:31)
  at <anonymous> (src/recipients/recipient.ts:241:14)
  at sort (native)
  at sortRecipients (src/recipients/recipient.ts:247:21)
  at executeFuzzySearch (src/recipients/recipient.ts:263:14)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by tarikbellamine**
### Description
Fix for toUpperCase error

### Other changes
No

### Tested
No

### Related issues
- Fixes #241

### Backwards compatibility
Yes

### CODE REVIEW

**Review by gnardini — COMMENTED** [review]
This fixes it for new users, but does it make sense to also add a check to the `nameCompare` function? Otherwise existing users will still crash when they open the send flow I assume?

File: packages/mobile/src/recipients/recipient.ts [hunk 1]
```diff
@@ -93,7 +94,7 @@ export function contactsToRecipients(contacts: MinimalContact[], defaultCountryC
           }
           e164NumberToRecipients[parsedNumber.e164Number] = {
             kind: RecipientKind.Contact,
-            displayName: contact.displayName,
+            displayName: contact.displayName || i18n.t('sendFlow7:mobileNumber'),
```
Comment (etuleu) [inline packages/mobile/src/recipients/recipient.ts:97]: What if we just populate this field with the actual phone number? just a thought, not really sure what's better

Comment (etuleu) [reply packages/mobile/src/recipients/recipient.ts:97]: Just curious: how come the displayName can be null since the interface has it non optional?

Comment (etuleu) [reply packages/mobile/src/recipients/recipient.ts:97]: I guess it can happen when reading from the addressbook there are no guarantees. But weird we haven't seen the crash so far. Also I agree we should add a check in the nameCompare function as well, or maybe use the getDisplayName function we already have which seems to do some null checking.

**Comment by tarikbellamine** [comment]
> This fixes it for new users, but does it make sense to also add a check to the nameCompare function? Otherwise existing users will still crash when they open the send flow I assume?

Yeah good point. I thought contacts were re-imported on some frequency but that's not the case. That's an issue because any contacts added after the initial Valora install probably won't be reflected in app. Problem for another PR though.

File: packages/mobile/src/recipients/recipient.ts (hunk 1 above)
Comment (tarikbellamine) [reply packages/mobile/src/recipients/recipient.ts:97]: Showing `mobileNumber` is consistent with how we deal with this elsewhere. `contact.displayName` should always be a string but for whatever reason that's not happening.

Not sure why this is showing up now though. I tried to track it down to changes we made in 1.12.2 but couldn't see how it's connected.

File: packages/mobile/src/recipients/recipient.ts [hunk 2]
```diff
@@ -213,8 +214,8 @@ function fuzzysortToRecipients(
 }
 
 function nameCompare(a: FuzzyRecipient, b: FuzzyRecipient) {
-  const nameA = a.displayName.toUpperCase()
-  const nameB = b.displayName.toUpperCase()
+  const nameA = a.displayName ? a.displayName.toUpperCase() : ''
```
Comment (gnardini) [inline packages/mobile/src/recipients/recipient.ts:217]: small nit: this could be written as `a.displayName?.toUpperCase() ?? ''` which looks a bit nicer imo, but I guess that's subjective :P

**Review by gnardini — APPROVED** [review]

**Comment by Lss-Ankit** [comment]
Hi @trianglesphere @etuleu  can you please provide more infor if we need to verify this issue ? 

Thanks!!

**Comment by tarikbellamine** [comment]
Hi @Lss-Ankit nothing is needed to test here. Thanks.
