### PR TITLE
Fix clock sync

### LINKED ISSUE #544: Fix clock drift calculation
The SetClock screen is opening when it shouldn't for many users.

Here's the code that calculates the time drift: https://github.com/celo-org/wallet/blob/main/packages/mobile/src/utils/time.ts#L294

We're first calling _Date.now()_ and then _getRemoteTime_, which makes a network request. If the request takes more than 4 seconds (the drift threshold) the date might be outdated and fail even when it shouldn't.

Improve this calculation. One idea is to get a _startingTime_ and _endTime_, before and after making the remote time request and check that the remote time is between `startingTime - 4s` and `endTime + 4s`

### PR DESCRIPTION
**Pull request by etuleu**
### Description

Looking at the logs provided in https://github.com/celo-org/wallet/issues/544 I noticed that when the clock sync check fails the drift is always 20 seconds. Then looking at the ntp library we are using here https://github.com/artem-russkikh/react-native-ntp-client/blob/master/lib/ntp-client.js it looks like the default timeout for the request is 10 seconds. Because we attempt 2 requests to 2 different ntp servers these add up to 20 seconds. Then the check fails because we want to be within 4 seconds. So if something is wrong with the network such as packet loss or udp port being blocked (which is pretty common on mobile devices) the check would always fail. Now it would be interesting to see what actually caused the timeout in this case.

The fix sets the ntp timeout to 2 seconds.

Of course there might be other issues causing this, such as the one we discussed where we don't account for the network delay roundtrip in the calculation.

Update: Looking at the history of this util function we used to use react-native-clock-sync which uses underneath react-native-ntp-client. The clock-sync lib keeps track of historical requests in order to estimate and adjust for network round trip delay. Using the ntp client directly does not do that as it is just a util that talks to ntp directly without any state.

### Other changes

I also modified the getRemoteTime function to return the initial start time in case of a timeout.

### Tested

In order to block the time servers we specify I modified the hosts file on my android emulator using the following steps roughly: block the time servers, then restart the app and notice after 10 seconds the clock sync screen shows up. There are probably other ways to test this but this is what I did locally using an android emulator:

Create a hosts file that looks something like:

`127.0.0.1       localhost`
`::1             ip6-localhost`
`172.0.0.1	time.google.com`
`172.0.0.1	time.cloudflare.com`
`

Now in order to push this file to the device we need to root the device.

> adb root
> adb disable-verity
> adb reboot
> adb root
> adb remount
> adb push hosts /etc/hosts

Now restart the app and wait 10 seconds to see the SetClock screen.

### How others should test

Start the app in various network conditions from really good wifi to bad signal mobile. Make sure the set clock screen does not show up after 5 seconds.

### Related issues

- Fixes #544 

### Backwards compatibility

Yes.

### CODE REVIEW

File: packages/mobile/src/utils/time.ts [hunk 1]
```diff
@@ -275,16 +277,19 @@ export const getDatetimeDisplayString = (timestamp: number, i18next: i18nType) =
 
 export const getRemoteTime = async () => {
   const getNetworkTime = promisify(ntpClient.getNetworkTime)
+  ntpClient.ntpReplyTimeout = 2000
```
Comment (gnardini) [inline packages/mobile/src/utils/time.ts:280]: In places with bad connection having the timeout be 2 seconds will most likely not be enough and we'll see a lot more timeouts.

IIRC the problem with having a bigger drift is that the light client will fail, right? I'm guessing very few people are using the light client and I don't think it works well anyways, so it might make sense to leave this like it was and change the drift tolerance to be 21 seconds instead.


As a side note, in the future if both these requests time out we need to retry at some point in the future, otherwise this is not doing anything really.

Comment (etuleu) [reply packages/mobile/src/utils/time.ts:280]: That was my initial thinking also but looking back at why @tarikbellamine added the ntp check in the first place it looks like fetching the pepper might want more accurate timestamps: https://github.com/celo-org/wallet/commit/bd5c02e51b66daa37dfb4536fec23057c6daa225#diff-a37126ff1aba3601ad5b60575833ea09d2484d1d816acc3938a7e8bd775cf9c8

I don't know how accurate it wants it to be though. Any ideas?

Comment (etuleu) [reply packages/mobile/src/utils/time.ts:280]: I will just make this 21 seconds as you suggested for now. As we learn more about what each service requires we can revisit this.

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R71](https://valora.testquality.com/project/12128/testcase/294979/requirement/11615).

**Comment by Celoqa** [comment]
Hi @MuckT We have verified this issue on Test flight build V1.17.0 and updated the status in test quality tool.

**Test quality tool link:**

**iOS (12.5.4):**
- https://valora.testquality.com/project/12128/plan/21240/run/149557/result/2450196

**New Issue:**
- https://github.com/celo-org/wallet/issues/930

**Devices:** Vivo v11 pro (10)

File: packages/mobile/src/utils/time.ts (hunk 1 above)
Comment (MuckT) [reply packages/mobile/src/utils/time.ts]: We could use something like [ts-retry-promise](https://www.npmjs.com/package/ts-retry-promise) to handle the retries with a backoff.
