### PR TITLE
Fix for tapping on a push notification on android

### LINKED ISSUE #161: Tapping a push notification on android does not open the webview always
### Expected Behavior

Tapping a push notification on android (such as the user survey) should open the app and show the webview. 

### Current Behavior

There are two states that don't work currently, namely app backgrounded via the back button or app swiped away. In both cases the app opens but does not handle the notification, so no webview is shown.

### PR DESCRIPTION
**Pull request by etuleu**
### Description

This is a fix for tapping on a push notification. Currently it is not handled properly if the app was backgrounded via the back button on android or swiped away (killed state).

We were setting up firebase too early in the app lifecycle. The firebase messaging setup needs to happen in sync with the App component because intents on android travel through Activities. This is mentioned briefly in the documentation here: https://rnfirebase.io/messaging/notifications

`The call to getInitialNotification should happen within a React lifecycle method after mounting (e.g. componentDidMount or useEffect). If it's called too soon (e.g. within a class constructor or global scope), the notification data may not be available.`

### Tested

On an android emulator using the push script then tapping on the notification to see if the webview shows up.

Here are the different scenarios tested.
1. Start app, send push notice blue notification bar shows up at the top with the notification message.
2. Kill app (swipe away), send push, tap on it from the android status bar, make sure the app opens and navigates to the webview.
3. Open app, press android home button (app goes to background but main activity is paused not destroyed), send push, tap on it, make sure webview opens.
4. Open app, press android back button (app goes to background with main activity destroyed), send push, tap on it, make sure webview opens.

I also made sure there aren't any obvious leaks in either the channel use to listen for notifications or the callbacks by printing and pressing back and reopening the app to make sure there aren't multiple. But I am not entirely sure if the cleanup is properly done, so hopefully someone can confirm.

Added a new e2e test that simulates opening the app from a notification. It is currently disabled because circle ci does not support firebase yet. It runs successfully locally and hopefully soon @non-binary and @MuckT will help support firebase on CI.

### Related issues

- Fixes #161 

### Backwards compatibility

Yes.

### CODE REVIEW

File: packages/mobile/src/firebase/saga.ts [hunk 1]
```diff
@@ -142,4 +156,5 @@ export function* firebaseSaga() {
   yield spawn(initializeFirebase)
   yield spawn(watchLanguage)
   yield spawn(subscribeToCeloGoldExchangeRateHistory)
+  yield takeLatest(AppActions.SET_APP_STATE, setupMessaging)
```
Comment (jeanregisser) [inline packages/mobile/src/firebase/saga.ts:159]: Conceptually, I would prefer to see this happening on a specific `APP_MOUNTED` action.
AppState API seems less natural / predictable for this, given the comment you made - that it needs to be linked to the App mounted lifecycle events.
What do you think?

Comment (etuleu) [reply packages/mobile/src/firebase/saga.ts:159]: That makes sense. Should be easy to create a new action APP_MOUNTED and its inverse. Then the rest of the code stays similar. I can change it to that. Also will feel safer knowing it happens after everything is mounted for sure.

File: packages/mobile/src/firebase/firebase.ts [hunk 2]
```diff
@@ -76,6 +77,58 @@ export const firebaseSignOut = async (app: ReactNativeFirebase.FirebaseApp) => {
...
+  }
+
+  // Manual type checking because yield calls can't infer return type yet :'(
+  const initialNotification: Awaited<ReturnType<
+    FirebaseMessagingTypes.Module['getInitialNotification']
+  >> = yield call([firebase.messaging(), 'getInitialNotification'])
+  if (initialNotification) {
+    Logger.info(TAG, 'App opened fresh via a notification', JSON.stringify(initialNotification))
+    yield call(handleNotification, initialNotification, NotificationReceiveState.APP_OPENED_FRESH)
+  }
```
Comment (jeanregisser) [inline packages/mobile/src/firebase/firebase.ts:129]: Looks like this shouldn't happen when `AppActions.APP_UNMOUNTED` initiated this, right?

Comment (etuleu) [reply packages/mobile/src/firebase/firebase.ts:129]: Yep, good catch! moved it inside the if statement so we only check it on app mounted.

File: packages/mobile/src/firebase/firebase.ts [hunk 3]
```diff
@@ -76,6 +77,58 @@ export const firebaseSignOut = async (app: ReactNativeFirebase.FirebaseApp) => {
...
+
+  Logger.debug(TAG, `setupMessage action: ${JSON.stringify(action)}`)
+
+  const isAppMounted = action.type === AppActions.APP_MOUNTED
+  if (isAppMounted) {
+    // TODO(erdal): is spawn the right one to use here?
+    yield spawn(watchFirebaseNotificationChannel, channelOnNotification)
+  } else {
+    channelOnNotification.close()
+  }
```
[the remark this answers is not in the document]
Comment (etuleu) [reply packages/mobile/src/firebase/firebase.ts]: This was a great suggestion! I looked where else we use takeLatest and rewrote it wire the app mounted event directly to the saga. As you intuited this eliminates the manual need to cancel the channel. I noticed it does get cancelled automatically on the next app mounted event, which corresponds to what the code does for takeLatest. I also made sure this doesn't cause a leak by connecting multiple channels. Thanks Jean!

[the remark this answers is not in the document]
Comment (etuleu) [reply packages/mobile/src/firebase/firebase.ts]: I also split the initial notification check into its own saga for more clarity. I really like how it's looking now!

File: packages/mobile/src/firebase/saga.ts [hunk 4]
```diff
@@ -142,4 +157,6 @@ export function* firebaseSaga() {
   yield spawn(initializeFirebase)
   yield spawn(watchLanguage)
   yield spawn(subscribeToCeloGoldExchangeRateHistory)
+  yield takeLatest(AppActions.APP_MOUNTED, watchFirebaseNotificationChannel)
```
Comment (gnardini) [inline packages/mobile/src/firebase/saga.ts:160]: `takeLatest` is not blocking, right? I ask because we do the `spawn` thing everywhere else, but if it's not blocking this looks fine :)

**Review by gnardini — APPROVED** [review]
Sorry for not reviewing earlier, this looks great 😄

File: packages/mobile/src/firebase/saga.ts (hunk 4 above)
Comment (etuleu) [reply packages/mobile/src/firebase/saga.ts:160]: Good question. The reason we wanted takeLatest is as per Jean's suggestion to not have to manually cancel. Here is the implementation: 

`const takeLatest = (patternOrChannel, saga, ...args) => fork(function*() {
  let lastTask
  while (true) {
    const action = yield take(patternOrChannel)
    if (lastTask) {
      yield cancel(lastTask) // cancel is no-op if the task has already terminated
    }
    lastTask = yield fork(saga, ...args.concat(action))
  }
})`

**Comment by Celoqa** [comment]
Hey @etuleu I have verified this issue using Android internal build V1.13.0 (1004294348) & observed following:
**Observations:**

- User able to receive Blue push notification & user able to redirect to celo.org web view page after tapping on it when app is foregrounded. Also it is observed that, continuous loading indicator not displayed after tapping on received blue notification. [Attachment](https://drive.google.com/file/d/1jpjk0WH3q3QieLHa6aR5yEnWCk96of6Z/view?usp=sharing)
- User able to receive push notification & user redirect to celo.org web view page after tapping on it without loading indicator when app is running in background using home button on android emulator.
- User able to receive push notification & user redirect to celo.org web view page after tapping on it without loading indicator when app is running in background using Back button on android emulator. Also we have observed that app takes some time (~5sec) on logo page & then redirect to web view. [Attachment](https://drive.google.com/file/d/1N4mXIVIgEvpzIatUp0iSuAD9c99XETiS/view?usp=sharing)
- User able to receive push notification & user redirect to celo.org web view page after tapping on it without loading indicator when app was swiped away(kill). Also it is observed that app takes same as 5 sec on logo page & now user gets first redirect to Home screen and after 20 second user redirect to web view. [Attachment](https://drive.google.com/file/d/1w6x1vsgAkJmrCikflcwzqa35z7mBQmtk/view?usp=sharing)

**Verified On Devices:** Samsung Galaxy A5(7.0)
Thanks..!!
