### PR TITLE
Fix device clock sync bug

### LINKED ISSUE #285: User is allowed to use Valora with unsycned clock
### Expected Behavior
If the user's device is not properly synced, they are sent to the `SetClock` screen and must sync their clock before proceeding.

### Current Behavior
User is not shown the `SetClock` screen when their clock is out of sync. It appears the package we are using `react-native-clock-sync` fails silently very often and in this case it just assumes remote time === local time. This package is no longer maintained and should probably be updated to something else, like this: https://www.npmjs.com/package/@jet-react/react-native-ntp-client

### PR DESCRIPTION
**Pull request by tarikbellamine**
### Description
Fix a bug where users were allowed to continue using Valora despite their device clocks being off. I first noticed this when debugging an issue with ODIS where pepper requests were failing due to outdated timestamps coming from the client. I suspect this may be having negative impacts on other services such as the Attestation service.

The package we were using `react-native-clock-sync` had a couple of issues filed for it and hadn't been updated in two years so I moved us to a better maintained package `react-native-npt-client`.

### Other changes
Refreshed the design on the `SetClock` screen as the formatting looked broken.

### Tested
Manually

### Related issues

- Fixes #285

### Backwards compatibility
Yes

IMG_0555

### CODE REVIEW

File: packages/mobile/src/set-clock/SetClock.tsx [hunk 1]
```diff
@@ -8,17 +8,28 @@ import { Image, Platform, StyleSheet, Text, View } from 'react-native'
...
+    this.setState({ correctTime })
+  }
 
-  goToSettings = () => {
+  goToSettingsOrRestart = () => {
     if (Platform.OS === 'android') {
       return AndroidOpenSettings.dateSettings()
     } else {
-      navigateHome()
+      restartApp()
```
Comment (gnardini) [inline packages/mobile/src/set-clock/SetClock.tsx:32]: 👀  lol

**Review by gnardini — APPROVED** [review]
Looks great!

On Android, if the user presses the button, goes to settings and fixes their clock then they open back their app they'll still see the `SetClock` screen, right? I guess it would be nice if we checked on app open if the clock thing was fixed and navigate home.  It still gets fixed by restarting and this probably doesn't affect a lot of users, so it's fine not to do that too though.

File: packages/mobile/src/account/reducer.ts [hunk 2]
```diff
@@ -188,7 +188,7 @@ export const reducer = (
     case Actions.SET_ACCOUNT_CREATION_TIME:
       return {
         ...state,
-        accountCreationTime: getRemoteTime(),
+        accountCreationTime: Date.now(),
```
Comment (jeanregisser) [inline packages/mobile/src/account/reducer.ts:191]: nothing to change now, but `now` should be passed from the action, reducers shouldn't have side effects.

**Review by jeanregisser — APPROVED** [review]
Thanks for fixing this!

On a side note, I hope we can eliminate the need for this screen in the future which is quite user unfriendly.
From what I remember, the main reason we need to enforce correct time was because of geth itself which can't sync properly when the clock is not right. But we are now using forno by default.

**Comment by tarikbellamine** [comment]
> From what I remember, the main reason we need to enforce correct time was because of geth itself which can't sync properly when the clock is not right. But we are now using forno by default.

Other services may rely on the user's device having an accurate time. For example, ODIS was throwing errors if the user's time was off by more than 10 mins.

File: packages/mobile/src/set-clock/SetClock.tsx (hunk 1 above)
Comment (etuleu) [inline packages/mobile/src/set-clock/SetClock.tsx:32]: I think restartApp might not work on iOS from what I remember with the forno toggle

Comment (tarikbellamine) [reply packages/mobile/src/set-clock/SetClock.tsx:32]: Yeah, it will just close the app. The button says "Quit" rather than "Restart" for that reason

File: packages/mobile/src/account/reducer.ts (hunk 2 above)
Comment (tarikbellamine) [reply packages/mobile/src/account/reducer.ts]: Good point. Went ahead and fixed it...no time like the present to chip away at some tech debt!

**Comment by tarikbellamine** [comment]
>I guess it would be nice if we checked on app open if the clock thing was fixed and navigate home. It still gets fixed by restarting and this probably doesn't affect a lot of users, so it's fine not to do that too though.

You're right. If it's easy to make the UX a little better, might as well do it. Thanks for the suggestion!

**Comment by jeanregisser** [comment]
> Other services may rely on the user's device having an accurate time. For example, ODIS was throwing errors if the user's time was off by more than 10 mins.

Yes the point is this should be invisible to the user. We can measure the drift and provide the adjusted "real" time for services that need it.
The current solution to ask for user to adjust their clock and come back to the app is not great.

**Comment by tarikbellamine** [comment]
> Yes the point is this should be invisible to the user. We can measure the drift and provide the adjusted "real" time for services that need it. The current solution to ask for user to adjust their clock and come back to the app is not great.

That's true and I agree. It's a bit complicated because some of the services (e.g., [ODIS directory of the SDK](https://github.com/celo-org/celo-monorepo/blob/da677b6b024a4c6e3c60917ceb9b44c56eac15e3/packages/sdk/identity/src/odis/phone-number-identifier.ts#L101)) use `Date.now()` in their packages rather than asking for the timestamp or using an NTP service. If we find all the places where an accurate time is needed, then we can collaborate with the necessary parties to make this more friendly UX
